#pragma kernel CSMain

//All matrices to be culled
StructuredBuffer<float4x4> IN_Matrices;
//Matrices of objects within frustum to get drawn
AppendStructuredBuffer<int> OUT_CulledMatrices;

//We will only use id.x so reduce y in numthreas to 1
[numthreads(1, 1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    //for now we are simply effectively copying on e buffer to another
    float4x4 transformationMatrix = IN_Matrices[id.x];
    OUT_CulledMatrices.Append(id.x);
}
